version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    expose:
      - 3000
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - .:/app
    command:
      "rails server --binding 0.0.0.0 --port 3000"
    env_file:
      - .env